name: Launchable Demo

on:
  pull_request:
  workflow_dispatch:

  env:
  LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN }}

jobs:
  PreMergeTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "adopt"
      - uses: actions/setup-python@v5
        with:
        python-version: '3.13'
      - name: Install Launchable command
        run: pip install --user --upgrade launchable~=1.0
      - name: Launchable verify
        run: launchable verify
      - name: Launchable record build
        run: launchable record build --name ${{ github.run_id }}
      - name: Compile
        run: mvn compile
      - name: Test
        run: mvn test
      - name: Launchable record tests
        if: always()
        run: launchable record tests maven ./**/target/surefire-reports
